name: phonon

channels:

  - conda-forge

dependencies:

  # MACE and LAMMPS won't work with python<3.10
  # Latest Python versions could break other dependencies
  - python=3.10

  - notebook>=7.0.0
  - matplotlib
  - numpy<2.0.0
  - scipy

  # LAMMPS NEEDS TO BE INSTALLED FROM liblammps.so
  # It's important to have mpi4py installed BEFORE
  # building the Python API of LAMMPS!
  - mpi4py  

  # Libraries for phonons
  - phonolammps
  - phonopy
  - dynaphopy
